# Use Node.js 18 or higher
FROM node:18-slim

# Create and change to the app directory
WORKDIR /app

# Copy application dependency manifests to the container image.
# A wildcard is used to ensure both package.json AND package-lock.json are copied.
# Copying this separately prevents re-running npm install on every code change.
COPY package*.json ./

# Install production dependencies.
RUN npm install --production

# Copy local code to the container image.
COPY . .

# Bind the port that the app listens to.
EXPOSE 10000

# Run the web service on container startup.
CMD [ "node", "server.js" ]
